"""remove char limit

Revision ID: a48072b767f9
Revises: c03794acabc9
Create Date: 2025-09-04 20:02:44.760363

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a48072b767f9'
down_revision = 'c03794acabc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove character limits from AgentRun table fields
    op.alter_column('agentrun', 'mail_sender',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'mail_subject',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'mail_body',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'status_message',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'draft_body',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'draft_subject',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    
    # Remove character limits from Step table fields
    op.alter_column('step', 'type',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('step', 'text',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('step', 'status',
                    existing_type=sa.VARCHAR(),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore character limits to Step table fields
    op.alter_column('step', 'status',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('step', 'text',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('step', 'type',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    
    # Restore character limits to AgentRun table fields
    op.alter_column('agentrun', 'draft_subject',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'draft_body',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'status_message',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'status',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'mail_body',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'mail_subject',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    op.alter_column('agentrun', 'mail_sender',
                    existing_type=sa.TEXT(),
                    type_=sa.VARCHAR(),
                    existing_nullable=False)
    # ### end Alembic commands ###
