"""create agent run and step table

Revision ID: c03794acabc9
Revises: 1a31ce608336
Create Date: 2025-09-04 11:54:20.529712

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c03794acabc9'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mail_sender', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mail_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mail_body', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('draft_body', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('draft_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agentrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_table('agentrun')
    # ### end Alembic commands ###
